Vagrant.configure(2) do |config|
  config.vm.box = 'centos/8'
  config.vm.box_url = 'centos/8'
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/Users/lsaidi/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
  config.vm.provision "file", source: "conf", destination: "/home/vagrant/apps"
  config.vm.define "yez-zainS" do |leader|
    leader.vm.hostname = "yez-zainS"
    leader.vm.network "private_network" , ip: "192.168.42.110"
    leader.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--name", "yez-zainS"]
    end
    leader.vm.provision "shell", path: 'scripts/k3s_installS.sh'
    leader.vm.provision "shell", path: 'scripts/setup_apps.sh'
  end
end