Vagrant.configure(2) do |config|
  config.vm.box = 'centos/8'
  config.vm.box_url = 'centos/8'
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/Users/lsaidi/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
  config.vm.provision "shell", path: 'scripts/init.sh'
  config.vm.define "yez-zainS" do |leader|
    leader.vm.hostname = "yez-zainS"
    leader.vm.network "private_network" , ip: "192.168.42.110"
    leader.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--name", "yez-zainS"]
    end
    leader.vm.provision "shell", path: 'scripts/k3s_installS.sh'
  end
  config.vm.define "yez-zainSW" do |follower|
    follower.vm.hostname = "yez-zainSW"
    follower.vm.network "private_network" , ip: "192.168.42.111"
    follower.ssh.insert_key = false
    follower.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--name", "yez-zainSW"]
    end
    # follower.vm.provision "shell", path: 'scripts/ks3_installSW.sh'
    follower.trigger.after :up do |trigger|
      trigger.run = {path: 'scripts/copy_token.sh'}
      trigger.run_remote = {path: 'scripts/k3s_installSW.sh'}
    end
  end
end