apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: dev
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: $REPO_URL
  password: $TOKEN
  username: Mr-lsaidi